% This test file was generated by Copilot. Validate generated output before use.
classdef GetSupportedInterfacesTest < matlab.unittest.TestCase
    methods(Test)
        function testSupportedInterfacesNotEmpty(testCase)
            interfaces = getSupportedInterfaces();
            testCase.verifyNotEmpty(interfaces, 'Supported interfaces should not be empty.');
        end

        function testSupportedInterfacesIsCellArray(testCase)
            interfaces = getSupportedInterfaces();
            testCase.verifyClass(interfaces, 'cell', 'Supported interfaces should be a cell array.');
        end

        function testSupportedInterfacesContainsExpectedInterface(testCase)
            interfaces = getSupportedInterfaces();
            expectedInterface = 'USB'; % Example expected interface
            testCase.verifyTrue(any(strcmp(interfaces, expectedInterface)), ...
                'Expected interface "%s" not found in supported interfaces.', expectedInterface);
        end
    end
end