% This test file was generated by Copilot. Validate generated output before use.
classdef SolveQuadraticTest < matlab.unittest.TestCase
    methods(Test)
        function testRealRoots(testCase)
            a = 1;
            b = -3;
            c = 2;
            expectedRoots = [2, 1];
            [actualRoots, D] = solveQuadratic(a, b, c);

            testCase.verifyEqual(actualRoots, expectedRoots);
            testCase.verifyGreaterThan(D, 0);
        end

        function testComplexRoots(testCase)
            a = 1;
            b = 2;
            c = 5;
            expectedRoots = [-1 + 2i, -1 - 2i];
            [actualRoots, D] = solveQuadratic(a, b, c);

            testCase.verifyEqual(actualRoots, expectedRoots, 'AbsTol', 1e-10);
            testCase.verifyLessThan(D, 0);
        end

        function testLinearCase(testCase)
            a = 0;
            b = 2;
            c = -4;
            expectedRoot = 2;
            [actualRoots, D] = solveQuadratic(a, b, c);

            testCase.verifyEqual(actualRoots(1), expectedRoot);
            testCase.verifyEqual(actualRoots(2), NaN);
            testCase.verifyEqual(D, NaN);
        end

        function testIndeterminateEquation(testCase)
            a = 0;
            b = 0;
            c = 0;
            testCase.verifyError(@() solveQuadratic(a, b, c), 'MATLAB:solveQuadratic:Indeterminate');
        end

        function testNoSolution(testCase)
            a = 0;
            b = 0;
            c = 5;
            testCase.verifyError(@() solveQuadratic(a, b, c), 'MATLAB:solveQuadratic:NoSolution');
        end
    end
end