name: MATLAB Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Instrument_Control_Toolbox
      - uses: matlab-actions/run-build@v2
        with:
          tasks: package
      - uses: actions/upload-artifact@v4
        with:
          name: toolbox
          path: quadDemo/release/quadDemo.mltbx
